parameters:
    btn_tag.form.type.select2_tags.class: Btn\TagBundle\Form\Type\Select2TagsType
    btn_tag.form.type.tag.class: Btn\TagBundle\Form\Type\TagType

services:
    btn_tag.form.type.select2_tags:
        class: %btn_tag.form.type.select2_tags.class%
        parent: btn_admin.form.type.select2_hidden
        calls:
            - [setEntityProvider, [@btn_tag.provider.tag]]
        tags:
            - { name: form.type, alias: btn_select2_tags }

    btn_tag.form.type.tag:
        class: %btn_tag.form.type.tag.class%
        calls:
            - [setEntityProvider, [@btn_tag.provider.tag]]
        tags:
            - { name: form.type, alias: btn_tag }
